{
 "title": "BeeGFS Client Operations (by User)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "aggregationPeriod",
    "label": "Aggregation Period",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "userid",
    "label": "User Id",
    "query": "import \"influxdata/influxdb/schema\"schema.measurementTagValues(  bucket: \"${bucket}\",  tag: \"user\",  measurement: \"storageClientOpsByUser\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Operation List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meta Operation List",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "  from(bucket: \"${bucket}\")    |> range(start: -${aggregationPeriod})    |> filter(fn: (r) => r._measurement == \"metaClientOpsByUser\")    |> sum()    |> group()     |> pivot(rowKey:[\"user\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
      }
     ]
    },
    {
     "title": "Storage Operation List",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")    |> range(start: -${aggregationPeriod})    |> filter(fn: (r) => r._measurement == \"storageClientOpsByUser\")    |> sum()    |> group()     |> pivot(rowKey:[\"user\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Meta Operation Per User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "User ID $userid",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "repeat": "userid",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")    |> range(start: -${aggregationPeriod})    |> filter(fn: (r) => r._measurement == \"metaClientOpsByUser\")    |> sum()    |> group()     |> pivot(rowKey:[\"user\"], columnKey: [\"_field\"], valueColumn: \"_value\")    |> filter(fn: (r) => r.user =~ /$userid$/)"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Operation Per User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "User ID $userid",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "repeat": "userid",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")    |> range(start: -${aggregationPeriod})    |> filter(fn: (r) => r._measurement == \"storageClientOpsByUser\")    |> sum()    |> group()     |> pivot(rowKey:[\"user\"], columnKey: [\"_field\"], valueColumn: \"_value\")    |> filter(fn: (r) => r.user =~ /$userid$/)"
      }
     ]
    }
   ]
  }
 ]
}