{
 "title": "BeeGFS Client Operations (by User)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "userid",
    "label": "User ID",
    "query": "import \"influxdata/influxdb/schema\"schema.measurementTagValues(  bucket: \"${bucket}\",  tag: \"user\",  measurement: \"storageClientOpsByUser\")"
   },
   { "name": "bucket", "label": "Bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  { "title": "Operation List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Meta Operation List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "  from(bucket: \"${bucket}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"metaClientOpsByUser\")\r\n    |> filter(fn: (r) => r.user =~ /${userid:regex}/)\r\n    |> sum()\r\n    |> group()\r\n     |> pivot(rowKey:[\"user\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Storage Operation List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"storageClientOpsByUser\")\r\n    |> filter(fn: (r) => r.user =~ /${userid:regex}/)\r\n    |> sum()\r\n    |> group()\r\n     |> pivot(rowKey:[\"user\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  { "title": "Meta Operation Per User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "User ID $userid",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "repeat": "userid",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"metaClientOpsByUser\")\r\n    |> sum()\r\n    |> group()\r\n     |> pivot(rowKey:[\"user\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> filter(fn: (r) => r.user =~ /$userid$/)"
    }
   ]
  },
  { "title": "Storage Operation Per User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "User ID $userid",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "repeat": "userid",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"storageClientOpsByUser\")\r\n    |> sum()\r\n    |> group()\r\n     |> pivot(rowKey:[\"user\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> filter(fn: (r) => r.user =~ /$userid$/)"
    }
   ]
  }
 ]
}