{
 "title": "BeeGFS Client Operations (by User)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aggregationPeriod",
    "label": "Aggregation Period",
    "query": "1s, 5s, 10s, 20s, 30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "userid",
    "query": "show tag values from storageClientOpsByUser with key = \"user\""
   }
  ]
 },
 "panels": [
  { "title": "Operation List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Meta Operation List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(*)   FROM \"metaClientOpsByUser\" WHERE time > now() - $aggregationPeriod GROUP BY \"user\"  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage Operation List",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT sum(*)   FROM \"storageClientOpsByUser\" WHERE time > now() - $aggregationPeriod GROUP BY \"user\" "
    }
   ]
  },
  {
   "title": "Meta Operation Per User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "User ID $userid",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "repeat": "userid",
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "query": "SELECT sum(\"close\") AS \"close\", sum(\"getXA\") AS \"getXA\", sum(\"hardlnk\") AS \"hardlnk\", sum(\"listXA\") AS \"listXA\", sum(\"mkdir\") AS \"mkdir\", sum(\"open\") AS \"open\", sum(\"rddir\") AS \"rddir\", sum(\"ren\") AS \"ren\", sum(\"rmXA\") AS \"rmXA\", sum(\"rmdir\") AS \"rmdir\", sum(\"setXA\") AS \"setXA\", sum(\"stat\") AS \"stat\", sum(\"statfs\") AS \"statfs\", sum(\"symlnk\") AS \"symlnk\", sum(\"trunc\") AS \"trunc\", sum(\"unlnk\") AS \"unlnk\", sum(\"ack\") AS \"ack\", sum(\"create\") AS \"create\", sum(\"createLI\") AS \"createLI\", sum(\"dirparent\") AS \"dirparent\", sum(\"entInf\") AS \"entInf\", sum(\"flckAp\") AS \"flckAp\",sum(\"flckEn\") AS \"flckEn\", sum(\"flckRg\") AS \"flckRg\", sum(\"fndOwn\") AS \"fndOwn\", sum(\"lookLI\")  AS \"lookLI\", sum(\"mdsInf\") AS \"mdsInf\", sum(\"mirror\") AS \"mirror\", sum(\"mvDirIns\") AS \"mvDirIns\", sum(\"mvFiIns\") AS \"mvFiIns\", sum(\"openLI\") AS \"openLI\", sum(\"refrEnt\") AS \"refrEnt\", sum(\"revalLI\") AS \"revalLI\", sum(\"rmLnk\") AS \"rmLnk\", sum(\"sAttr\") AS \"sAttr\", sum(\"sChDrct\") AS \"sChDrct\", sum(\"sDirPat\") AS \"sDirPat\", sum(\"statLI\") AS \"statLI\"  FROM \"metaClientOpsByUser\" WHERE time > now() - $aggregationPeriod AND (\"user\" =~ /^$userid$/) "
      }
     ]
    }
   ]
  },
  { "title": "Storage Operation Per User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "User ID $userid",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "repeat": "userid",
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "storageClientOpsByUser",
     "query": "SELECT sum(\"ack\") AS \"ack\", sum(\"close\") AS \"close\", sum(\"fsync\") AS \"fsync\", sum(\"gendbg\") AS \"gendbg\", sum(\"getFSize\") AS \"getFSize\", sum(\"hrtbeat\") AS \"hrtbeat\", sum(\"ops-rd\") AS \"ops-rd\", sum(\"ops-wr\") AS \"ops-wr\", sum(\"remNode\") AS \"remNode\", sum(\"sAttr\") AS \"sAttr\", sum(\"sChDrct\") AS \"sChDrct\", sum(\"statfs\") AS \"statfs\", sum(\"storInf\") AS \"storInf\",  sum(\"trunc\") AS \"trunc\", sum(\"unlnk\") AS \"unlnk\" FROM \"storageClientOpsByUser\" WHERE time > now() - $aggregationPeriod AND (\"user\" =~ /^$userid$/) ",
     "select": [
      [
       { "params": [ "B-wr" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "write" ], "type": "alias" }
      ],
      [
       { "params": [ "B-rd" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$userid$/" }
     ]
    }
   ]
  }
 ]
}