{
 "title": "BeeGFS Meta Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metaID",
    "label": "Meta ID",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"nodeNumID\",\r\n  measurement: \"meta\"\r\n)"
   },
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "cpu",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"${bucket}\", tag: \"cpu\")"
   },
   {
    "name": "hostmeta",
    "label": "Meta Host",
    "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.nodeNumID == \"${metaID}\" and     r._measurement == \"meta\" and    r._field == \"hostnameid\") |> last()"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostmeta}\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.host == \"${hostmeta}\" and     r._measurement == \"system\" and    r._field == \"n_cpus\")  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")  \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \r\n|> filter(fn: (r) =>    r.host == \"${hostmeta}\" and     r._measurement == \"mem\" and    r._field == \"total\")  \r\n|> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)  \r\n|> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "meta",
     "query": "from(bucket: \"${bucket}\")  \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \r\n|> filter(fn: (r) =>    r.nodeNumID == \"${metaID}\" and     r._measurement == \"meta\" and    r._field == \"isResponding\")  \r\n|> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)  \r\n|> yield(name: \"last\")  \r\n|> keep(columns: [\"_time\",\"_value\"])",
     "select": [
      [
       { "params": [ "isResponding" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_threads\")\r\n  |> filter(fn: (r) =>  r.host == \"${hostmeta}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> filter(fn: (r) =>  r.host == \"${hostmeta}\")\r\n  |> last()\r\n  |> drop(columns: [\"_measurement\", \"_field\", \"_start\", \"_stop\", \"time\", \"host\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\" or r[\"_field\"] == \"n_cpus\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostmeta}\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with n_cpus: float(v: r.n_cpus)}))\r\n  |> map(fn: (r) => ({ r with load1_percore: r.load1 / r.n_cpus}))\r\n  |> drop(columns: [\"_measurement\", \"load1\", \"n_cpus\", \"host\", \"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Load 5m",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"load5\" or r[\"_field\"] == \"n_cpus\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostmeta}\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with n_cpus: float(v: r.n_cpus)}))\r\n  |> map(fn: (r) => ({ r with load5_percore: r.load5 / r.n_cpus}))\r\n  |> drop(columns: [\"_measurement\", \"load5\", \"n_cpus\", \"host\", \"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Load 15m",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"load15\" or r[\"_field\"] == \"n_cpus\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostmeta}\")\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with n_cpus: float(v: r.n_cpus)}))\r\n  |> map(fn: (r) => ({ r with load15_percore: r.load15 / r.n_cpus}))\r\n  |> drop(columns: [\"_measurement\", \"load15\", \"n_cpus\", \"host\", \"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Memory Used %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"available_percent\")\r\n  |> filter(fn: (r) =>  r.host == \"${hostmeta}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(fn: (column) => column =~ /^_(start|stop)/)\r\n  |> map(fn: (r) => ({r with usedmemory: 100.0 - r.available_percent}))\r\n  |> drop(fn: (column) => column =~ /available_percent/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResMeta",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.nodeNumID == \"${metaID}\" and \r\n    r._measurement == \"highResMeta\" and\r\n    r._field == \"netRecvBytes\")\r\n  |> group(columns: [\"nodeNumID\"], mode: \"by\")\r\n  |> aggregateWindow(every: 10s, fn: max, createEmpty: false)\r\n  |> rename(columns: {_value: \"Received\"})",
     "select": [
      [
       { "params": [ "netRecvBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Sent",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResMeta",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.nodeNumID == \"${metaID}\" and \r\n    r._measurement == \"highResMeta\" and\r\n    r._field == \"netSendBytes\")\r\n  |> group(columns: [\"nodeNumID\"], mode: \"by\")\r\n  |> aggregateWindow(every: 10s, fn: max, createEmpty: false)\r\n  |> rename(columns: {_value: \"Send\"})",
     "select": [
      [
       { "params": [ "netSendBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Work Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "alias": "Processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "highResMeta",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.nodeNumID == \"${metaID}\" and \r\n    r._measurement == \"highResMeta\" and\r\n    r._field == \"workRequests\")\r\n  |> group(columns: [\"nodeNumID\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> rename(columns: {_value: \"Processed\"})",
     "select": [
      [
       { "params": [ "workRequests" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Queued",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResMeta",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.nodeNumID == \"${metaID}\" and \r\n    r._measurement == \"highResMeta\" and\r\n    r._field == \"queuedRequests\")\r\n  |> group(columns: [\"nodeNumID\"], mode: \"by\") \r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> rename(columns: {_value: \"Queued\"})",
     "select": [
      [
       { "params": [ "queuedRequests" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Worklist Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "Direct",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "meta",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.nodeNumID == \"${metaID}\" and \r\n    r._measurement == \"meta\" and\r\n    r._field == \"directWorkListSize\")\r\n  |> group(columns: [\"nodeNumID\"], mode: \"by\") \r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> rename(columns: {_value: \"Direct\"})",
     "select": [
      [
       { "params": [ "directWorkListSize" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Indirect",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "meta",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.nodeNumID == \"${metaID}\" and \r\n    r._measurement == \"meta\" and\r\n    r._field == \"indirectWorkListSize\")\r\n  |> group(columns: [\"nodeNumID\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> rename(columns: {_value: \"Indirect\"})",
     "select": [
      [
       { "params": [ "indirectWorkListSize" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\" or r[\"_field\"] == \"load5\" or r[\"_field\"] == \"load15\")\r\n  |> filter(fn: (r) => r.host == \"${hostmeta}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\" or r[\"_field\"] == \"usage_system\" or r[\"_field\"] == \"usage_iowait\")\r\n  |> filter(fn: (r) => r.host == \"${hostmeta}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "from(bucket: \"${bucket}\")  \r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)  \r\n|> filter(fn: (r) => r[\"_measurement\"] == \"processes\")  \r\n|> filter(fn: (r) => r[\"_field\"] == \"running\" or r[\"_field\"] == \"blocked\" or r[\"_field\"] == \"sleeping\" or r[\"_field\"] == \"stopped\" or r[\"_field\"] == \"zombies\")  \r\n|> filter(fn: (r) => r.host == \"${hostmeta}\")  \r\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)  \r\n|> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage per core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\r\n  |> filter(fn: (r) => r[\"cpu\"] =~ /cpu[0-9].*/)\r\n  |> filter(fn: (r) => r.host == \"${hostmeta}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(fn: (column) => column =~ /^_(start|stop)/)\r\n  |> map(fn: (r) => ({r with usage_idle: 100.0 - r.usage_idle}))"
    }
   ]
  },
  {
   "title": " RAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "  from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) => r.host == \"${hostmeta}\")\r\n  |> filter(fn: (r) => r._measurement == \"mem\")\r\n  |> filter(fn: (r) => r._field == \"available\" or r._field == \"buffered\" or r._field == \"free\" or r._field == \"cached\" or r._field == \"used\" or r._field == \"total\" or r._field == \"mapped\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Buffered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$metaID$/" }
     ]
    },
    {
     "alias": "Mapped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "mapped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  }
 ]
}