{
 "title": "BeeGFS Storage Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "storageID",
    "query": "import \"influxdata/influxdb/schema\"schema.measurementTagValues(  bucket: \"${bucket}\",  tag: \"nodeNumID\",  measurement: \"storage\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.nodeNumID == \"${storageID}\" and     r._measurement == \"highResStorage\" and    r._field == \"diskReadBytes\") |> group(columns: [\"nodeNumID\"], mode: \"by\")  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> rename(columns: {_value: \"Read\"})",
     "select": [
      [
       { "params": [ "diskReadBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.nodeNumID == \"${storageID}\" and     r._measurement == \"highResStorage\" and    r._field == \"diskWriteBytes\") |> group(columns: [\"nodeNumID\"], mode: \"by\") |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> rename(columns: {_value: \"Write\"})",
     "select": [
      [
       { "params": [ "diskWriteBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "DiskSpaceFree",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "from(bucket: \"${bucket}\")  \r\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \r\n|> filter(fn: (r) => r.nodeNumID == \"${storageID}\")\r\n|> filter(fn: (r) => r._measurement == \"storage\")\r\n|> filter(fn: (r) => r._field == \"diskSpaceTotal\" or r._field == \"diskSpaceFree\")  \r\n|> group(columns: [\"nodeNumID\"], mode: \"by\")\r\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ r with _value: r.diskSpaceTotal - r.diskSpaceFree }))\r\n|> rename(columns: {_value: \"diskSpaceUsed\"})",
     "select": [
      [
       { "params": [ "diskSpaceFree" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.nodeNumID == \"${storageID}\" and     r._measurement == \"highResStorage\" and    r._field == \"netRecvBytes\")  |> group(columns: [\"nodeNumID\"], mode: \"by\") |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> rename(columns: {_value: \"Received\"})",
     "select": [
      [
       { "params": [ "netRecvBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    },
    {
     "alias": "Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.nodeNumID == \"${storageID}\" and     r._measurement == \"highResStorage\" and    r._field == \"netSendBytes\") |> group(columns: [\"nodeNumID\"], mode: \"by\") |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> rename(columns: {_value: \"Send\"})",
     "select": [
      [
       { "params": [ "netSendBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    }
   ]
  },
  {
   "title": "Work Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.nodeNumID == \"${storageID}\" and     r._measurement == \"highResStorage\" and    r._field == \"workRequests\") |> group(columns: [\"nodeNumID\"], mode: \"by\") |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> rename(columns: {_value: \"Processed\"})",
     "select": [
      [
       { "params": [ "workRequests" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    },
    {
     "alias": "Queued",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.nodeNumID == \"${storageID}\" and     r._measurement == \"highResStorage\" and    r._field == \"queuedRequests\") |> group(columns: [\"nodeNumID\"], mode: \"by\") |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> rename(columns: {_value: \"Queued\"})",
     "select": [
      [
       { "params": [ "queuedRequests" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Availability",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "meta",
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.nodeNumID == \"${storageID}\" and     r._measurement == \"storage\" and    r._field == \"isResponding\") |> group(columns: [\"nodeNumID\"], mode: \"by\") |> keep(columns: [\"_time\", \"_value\"])  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "isResponding" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$metaID$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Targets ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageTargetID" ], "type": "tag" }
     ],
     "measurement": "storageTargets",
     "query": "  from(bucket: \"${bucket}\")    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)    |> filter(fn: (r) => r.nodeNumID == \"${storageID}\" and r._measurement == \"storageTargets\" and r._field == \"diskSpaceTotal\")    |> group(columns: [\"storageTargetID\"])    |> last()    |> group()    |> keep(columns: [\"_value\", \"storageTargetID\"])    |> rename(columns: {_value: \"Total Space\"})",
     "select": [
      [
       { "params": [ "diskSpaceTotal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "totalspace" ], "type": "alias" }
      ],
      [
       { "params": [ "diskSpaceFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "freespace" ], "type": "alias" }
      ],
      [
       { "params": [ "targetConsistencyState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    },
    {
     "query": "  from(bucket: \"${bucket}\")    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)    |> filter(fn: (r) => r.nodeNumID == \"${storageID}\" and r._measurement == \"storageTargets\" and r._field == \"diskSpaceFree\")    |> group(columns: [\"storageTargetID\"])    |> last()    |> group()    |> keep(columns: [\"_value\", \"storageTargetID\"])    |> rename(columns: {_value: \"Free Space\"})"
    },
    {
     "query": "  from(bucket: \"${bucket}\")    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)    |> filter(fn: (r) => r.nodeNumID == \"${storageID}\" and r._measurement == \"storageTargets\" and r._field == \"targetConsistencyState\")    |> group(columns: [\"storageTargetID\"])    |> last()    |> group()    |> keep(columns: [\"_value\", \"storageTargetID\"])    |> rename(columns: {_value: \"State\"})"
    }
   ]
  }
 ]
}