{
 "title": "BeeGFS Storage Targets",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "storageID",
    "query": "import \"influxdata/influxdb/schema\"schema.measurementTagValues(  bucket: \"${bucket}\",  tag: \"nodeID\",  measurement: \"storage\")"
   },
   {
    "name": "storageTargetID",
    "query": "import \"influxdata/influxdb/schema\"schema.tagValues(    bucket: \"${bucket}\",    tag: \"storageTargetID\",    predicate: (r) => r._measurement == \"storageTargets\" and r.nodeID == \"${storageID:\"\"}\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.storageTargetID == \"${storageTargetID}\" and     r._measurement == \"storageTargets\" and    r._field == \"diskSpaceTotal\")  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> yield(name: \"max\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.storageTargetID == \"${storageTargetID}\" and     r._measurement == \"storageTargets\" and    r._field == \"diskSpaceFree\")  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.storageTargetID == \"${storageTargetID}\" and     r._measurement == \"storageTargets\" and    r._field == \"inodesTotal\")  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> yield(name: \"max\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.storageTargetID == \"${storageTargetID}\" and     r._measurement == \"storageTargets\" and    r._field == \"inodesFree\")  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Target Consistency State",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": " from(bucket: \"${bucket}\")  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  |> filter(fn: (r) =>    r.storageTargetID == \"${storageTargetID}\" and     r._measurement == \"storageTargets\" and    r._field == \"targetConsistencyState\") |> last()    |> group()  |> rename(columns: {_value: \"State\"})"
    }
   ]
  }
 ]
}