package com.beegfs.admon.gui.components.frames;

import com.beegfs.admon.gui.common.enums.UpdateDataTypeEnum;
import com.beegfs.admon.gui.components.internalframes.JInternalFrameUpdateableInterface;
import java.util.ArrayList;


public class JFrameAddHosts extends javax.swing.JFrame
{
   private static final long serialVersionUID = 1L;

   private final static int INITIAL_CAPACITY = 10;

   private final JInternalFrameUpdateableInterface parent;
   private final UpdateDataTypeEnum type;

   /**
    * Creates new form JFrameAddHost
    *
    * @param parent The parent frame.
    * @param type The the type of data to update.
    */
   public JFrameAddHosts(JInternalFrameUpdateableInterface parent, UpdateDataTypeEnum type)
   {
      this.parent = parent;
      this.type = type;

      initComponents();
      this.setTitle(type.getTitle() );
      this.jTextFieldHost0.requestFocus();
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jPanelFrame = new javax.swing.JPanel();
      jPanelButtons = new javax.swing.JPanel();
      jButtonAdd = new javax.swing.JButton();
      jButtonCancel = new javax.swing.JButton();
      jPanelHosts = new javax.swing.JPanel();
      jTextFieldHost0 = new javax.swing.JTextField();
      jTextFieldHost1 = new javax.swing.JTextField();
      jTextFieldHost2 = new javax.swing.JTextField();
      jTextFieldHost3 = new javax.swing.JTextField();
      jTextFieldHost4 = new javax.swing.JTextField();
      jTextFieldHost5 = new javax.swing.JTextField();
      jTextFieldHost6 = new javax.swing.JTextField();
      jTextFieldHost7 = new javax.swing.JTextField();
      jTextFieldHost8 = new javax.swing.JTextField();
      jTextFieldHost9 = new javax.swing.JTextField();
      jScrollPaneDescription = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setAlwaysOnTop(true);
      setResizable(false);

      jPanelFrame.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
      jPanelFrame.setLayout(new java.awt.BorderLayout());

      jPanelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 0));

      jButtonAdd.setText("Add");
      jButtonAdd.setMaximumSize(new java.awt.Dimension(70, 30));
      jButtonAdd.setMinimumSize(new java.awt.Dimension(70, 30));
      jButtonAdd.setPreferredSize(new java.awt.Dimension(100, 32));
      jButtonAdd.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButtonAddActionPerformed(evt);
         }
      });
      jPanelButtons.add(jButtonAdd);

      jButtonCancel.setText("Cancel");
      jButtonCancel.setPreferredSize(new java.awt.Dimension(100, 32));
      jButtonCancel.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButtonCancelActionPerformed(evt);
         }
      });
      jPanelButtons.add(jButtonCancel);

      jPanelFrame.add(jPanelButtons, java.awt.BorderLayout.SOUTH);

      jPanelHosts.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
      jPanelHosts.setLayout(new java.awt.GridLayout(10, 1, 5, 5));
      jPanelHosts.add(jTextFieldHost0);
      jPanelHosts.add(jTextFieldHost1);
      jPanelHosts.add(jTextFieldHost2);
      jPanelHosts.add(jTextFieldHost3);
      jPanelHosts.add(jTextFieldHost4);
      jPanelHosts.add(jTextFieldHost5);
      jPanelHosts.add(jTextFieldHost6);
      jPanelHosts.add(jTextFieldHost7);
      jPanelHosts.add(jTextFieldHost8);
      jPanelHosts.add(jTextFieldHost9);

      jPanelFrame.add(jPanelHosts, java.awt.BorderLayout.CENTER);

      jScrollPaneDescription.setBorder(null);
      jScrollPaneDescription.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
      jScrollPaneDescription.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

      jTextArea1.setEditable(false);
      jTextArea1.setBackground(new java.awt.Color(238, 238, 238));
      jTextArea1.setColumns(20);
      jTextArea1.setLineWrap(true);
      jTextArea1.setRows(5);
      jTextArea1.setText("Please insert the names of the hosts to add.\n\nCou can leave remaining fields blank.");
      jTextArea1.setWrapStyleWord(true);
      jTextArea1.setBorder(null);
      jScrollPaneDescription.setViewportView(jTextArea1);

      jPanelFrame.add(jScrollPaneDescription, java.awt.BorderLayout.NORTH);

      getContentPane().add(jPanelFrame, java.awt.BorderLayout.CENTER);

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
      ArrayList<String> hosts = new ArrayList<>(INITIAL_CAPACITY);
      hosts.add(jTextFieldHost0.getText());
      hosts.add(jTextFieldHost1.getText());
      hosts.add(jTextFieldHost2.getText());
      hosts.add(jTextFieldHost3.getText());
      hosts.add(jTextFieldHost4.getText());
      hosts.add(jTextFieldHost5.getText());
      hosts.add(jTextFieldHost6.getText());
      hosts.add(jTextFieldHost7.getText());
      hosts.add(jTextFieldHost8.getText());
      hosts.add(jTextFieldHost9.getText());

      parent.updateData(hosts, type);

      this.dispose();
}//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
      this.dispose();
}//GEN-LAST:event_jButtonCancelActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonAdd;
   private javax.swing.JButton jButtonCancel;
   private javax.swing.JPanel jPanelButtons;
   private javax.swing.JPanel jPanelFrame;
   private javax.swing.JPanel jPanelHosts;
   private javax.swing.JScrollPane jScrollPaneDescription;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextField jTextFieldHost0;
   private javax.swing.JTextField jTextFieldHost1;
   private javax.swing.JTextField jTextFieldHost2;
   private javax.swing.JTextField jTextFieldHost3;
   private javax.swing.JTextField jTextFieldHost4;
   private javax.swing.JTextField jTextFieldHost5;
   private javax.swing.JTextField jTextFieldHost6;
   private javax.swing.JTextField jTextFieldHost7;
   private javax.swing.JTextField jTextFieldHost8;
   private javax.swing.JTextField jTextFieldHost9;
   // End of variables declaration//GEN-END:variables

}
