package com.beegfs.admon.gui.components.charts;


import java.awt.Color;


public class LegendItemToggable extends javax.swing.JPanel
{
   private static final long serialVersionUID = 1L;

   private final LineChart chart;

   /**
    * Creates new form LegendItemToggable
    */
   public LegendItemToggable(LineChart chart, Color color, String name)
   {
      initComponents();
      this.jCheckBoxName.setText(name);
      this.jPanelColor.setBackground(color);
      this.chart = chart;
   }

   @Override
   public String getName()
   {
      return jCheckBoxName.getText();
   }

   @Override
   public void setEnabled(boolean enabled)
   {
      super.setEnabled(enabled);
      jPanelColor.setEnabled(enabled);
      jCheckBoxName.setEnabled(enabled);
   }

   public void selectCheckbox()
   {
      jCheckBoxName.setSelected(true);
   }

   public void deselectCheckbox()
   {
      jCheckBoxName.setSelected(false);
   }

   public boolean isCheckboxSelected()
   {
      return jCheckBoxName.isSelected();
   }
   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jPanelColor = new javax.swing.JPanel();
      jCheckBoxName = new javax.swing.JCheckBox();

      FormListener formListener = new FormListener();

      setBackground(javax.swing.UIManager.getDefaults().getColor("white"));
      setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

      jPanelColor.setPreferredSize(new java.awt.Dimension(14, 14));

      javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
      jPanelColor.setLayout(jPanelColorLayout);
      jPanelColorLayout.setHorizontalGroup(
         jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 14, Short.MAX_VALUE)
      );
      jPanelColorLayout.setVerticalGroup(
         jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 14, Short.MAX_VALUE)
      );

      add(jPanelColor);

      jCheckBoxName.setBackground(javax.swing.UIManager.getDefaults().getColor("white"));
      jCheckBoxName.setText("TraceX");
      jCheckBoxName.addActionListener(formListener);
      add(jCheckBoxName);
   }

   // Code for dispatching events from components to event handlers.

   private class FormListener implements java.awt.event.ActionListener
   {
      FormListener() {}
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
         if (evt.getSource() == jCheckBoxName)
         {
            LegendItemToggable.this.jCheckBoxNameActionPerformed(evt);
         }
      }
   }// </editor-fold>//GEN-END:initComponents

   private void jCheckBoxNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxNameActionPerformed
   {//GEN-HEADEREND:event_jCheckBoxNameActionPerformed
      if (jCheckBoxName.isSelected())
      {
         chart.enableTrace(jCheckBoxName.getText());
      }
      else
      {
         chart.disableTrace(jCheckBoxName.getText());
      }
   }//GEN-LAST:event_jCheckBoxNameActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JCheckBox jCheckBoxName;
   private javax.swing.JPanel jPanelColor;
   // End of variables declaration//GEN-END:variables
}
