package com.beegfs.admon.gui.components.charts;


import java.awt.Color;



public class LegendItemNotToggable extends javax.swing.JPanel
{
   private static final long serialVersionUID = 1L;

   private final LineChart chart;

   /**
    * Creates new form LegendItemNotToggable
    */
   public LegendItemNotToggable(LineChart chart, Color color, String name)
   {
      initComponents();
      this.jLabelName.setText(name);
      this.jPanelColor.setBackground(color);
      this.chart = chart;
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jPanelColor = new javax.swing.JPanel();
      jLabelName = new javax.swing.JLabel();

      setBackground(javax.swing.UIManager.getDefaults().getColor("white"));
      setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

      jPanelColor.setMaximumSize(new java.awt.Dimension(14, 14));
      jPanelColor.setMinimumSize(new java.awt.Dimension(14, 14));
      jPanelColor.setPreferredSize(new java.awt.Dimension(14, 14));

      javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
      jPanelColor.setLayout(jPanelColorLayout);
      jPanelColorLayout.setHorizontalGroup(
         jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 14, Short.MAX_VALUE)
      );
      jPanelColorLayout.setVerticalGroup(
         jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 14, Short.MAX_VALUE)
      );

      add(jPanelColor);

      jLabelName.setBackground(javax.swing.UIManager.getDefaults().getColor("white"));
      jLabelName.setText("TraceX");
      add(jLabelName);
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabelName;
   private javax.swing.JPanel jPanelColor;
   // End of variables declaration//GEN-END:variables
}
