package com.beegfs.admon.gui.components.dialogs;

import com.beegfs.admon.gui.common.enums.PropertyEnum;
import com.beegfs.admon.gui.common.tools.GuiTk;
import com.beegfs.admon.gui.program.Main;
import java.io.File;
import java.util.Locale;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

public class JDialogNewConfig extends javax.swing.JDialog
{
   private static final long serialVersionUID = 1L;

   private boolean abortPushed;

   /**
    * Creates new form JDialogNewConfig
    */
   public JDialogNewConfig(java.awt.Frame parent, boolean modal)
   {
      super(parent, modal);
      initComponents();
      this.setIconImage(GuiTk.getFrameIcon().getImage());
      this.setLocationRelativeTo(null);
      this.abortPushed = false;
      jTextFieldHostname.setText(Main.getConfig().getAdmonHost());
      jTextFieldPort.setText(String.valueOf(Main.getConfig().getAdmonHttpPort()));
      jTextResolution.setText(Main.getConfig().getResolution());
      jComboBoxLogLevel.setSelectedIndex(Main.getConfig().getLogLevelNumeric());
      jComboBoxLocal.setSelectedItem(Main.getConfig().getAdmonLocal());
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      java.awt.GridBagConstraints gridBagConstraints;

      jPanelDialog = new javax.swing.JPanel();
      jScrollPaneDescription = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();
      jLabelHostname = new javax.swing.JLabel();
      jLabelPort = new javax.swing.JLabel();
      jTextFieldPort = new javax.swing.JTextField();
      jTextFieldHostname = new javax.swing.JTextField();
      jButtonSave = new javax.swing.JButton();
      jButtonClose = new javax.swing.JButton();
      jLabelResolution = new javax.swing.JLabel();
      jTextResolution = new javax.swing.JTextField();
      jLabelLogLevel = new javax.swing.JLabel();
      jComboBoxLogLevel = new javax.swing.JComboBox<>();
      jLabelLocal = new javax.swing.JLabel();
      jComboBoxLocal = new javax.swing.JComboBox<>();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle(Main.getLocal().getString("Write GUI configuration"));

      jPanelDialog.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
      jPanelDialog.setLayout(new java.awt.GridBagLayout());

      jTextArea1.setEditable(false);
      jTextArea1.setColumns(20);
      jTextArea1.setLineWrap(true);
      jTextArea1.setRows(2);
      jTextArea1.setText(Main.getLocal().getString("Please provide some information on how to connect to the BeeGFS administration and monitoring daemon."));
      jTextArea1.setWrapStyleWord(true);
      jScrollPaneDescription.setViewportView(jTextArea1);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.gridwidth = 3;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.weighty = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
      jPanelDialog.add(jScrollPaneDescription, gridBagConstraints);

      jLabelHostname.setText(Main.getLocal().getString("Hostname where the daemon runs : "));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
      jPanelDialog.add(jLabelHostname, gridBagConstraints);

      jLabelPort.setText(Main.getLocal().getString("HTTP-Port the daemon uses : "));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
      jPanelDialog.add(jLabelPort, gridBagConstraints);

      jTextFieldPort.setText("8000");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
      jPanelDialog.add(jTextFieldPort, gridBagConstraints);

      jTextFieldHostname.setText("localhost");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
      jPanelDialog.add(jTextFieldHostname, gridBagConstraints);

      jButtonSave.setText(Main.getLocal().getString("Save"));
      jButtonSave.setMaximumSize(new java.awt.Dimension(80, 30));
      jButtonSave.setMinimumSize(new java.awt.Dimension(80, 30));
      jButtonSave.setPreferredSize(new java.awt.Dimension(80, 30));
      jButtonSave.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButtonSaveActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 6; 
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
      jPanelDialog.add(jButtonSave, gridBagConstraints);

      jButtonClose.setText(Main.getLocal().getString("Abort"));
      jButtonClose.setMaximumSize(new java.awt.Dimension(80, 30));
      jButtonClose.setMinimumSize(new java.awt.Dimension(80, 30));
      jButtonClose.setPreferredSize(new java.awt.Dimension(80, 30));
      jButtonClose.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButtonCloseActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.gridy = 6; 
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
      jPanelDialog.add(jButtonClose, gridBagConstraints);

      jLabelResolution.setText(Main.getLocal().getString("Internal desktop resolution: "));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
      jPanelDialog.add(jLabelResolution, gridBagConstraints);

      jTextResolution.setText("1024x768");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
      jPanelDialog.add(jTextResolution, gridBagConstraints);

      jLabelLogLevel.setText(Main.getLocal().getString("Log level: "));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 4;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
      jPanelDialog.add(jLabelLogLevel, gridBagConstraints);

      jComboBoxLogLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 4;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
      jPanelDialog.add(jComboBoxLogLevel, gridBagConstraints);

      jLabelLocal.setText(Main.getLocal().getString("Language: "));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 5;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
      jPanelDialog.add(jLabelLocal, gridBagConstraints);

      jComboBoxLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { Main.getLocal().getString("English"), Main.getLocal().getString("Chinese") }));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 5;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
      jPanelDialog.add(jComboBoxLocal, gridBagConstraints);


      getContentPane().add(jPanelDialog, java.awt.BorderLayout.CENTER);

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
      this.abortPushed = false;
      String hostname = jTextFieldHostname.getText();
      int port;

      try
      {
         port = Integer.parseInt(jTextFieldPort.getText());
      }
      catch (NumberFormatException e)
      {
    	  JOptionPane.showMessageDialog(null, Main.getLocal().getString("Please provide a number as port value"),
    		 Main.getLocal().getString("Wrong port value"), JOptionPane.ERROR_MESSAGE);
         return;
      }

      boolean validResolution = Main.getConfig().setResolution(jTextResolution.getText());
      if(!validResolution)
      {
    	  JOptionPane.showMessageDialog(null, Main.getLocal().getString("Please provide a valid resolution value. Example: ") +
    		"2048x2048 ", Main.getLocal().getString("Wrong resolution value"), JOptionPane.ERROR_MESSAGE);
         return;
      }

      Main.getConfig().setAdmonHost(hostname);
      Main.getConfig().setAdmonHttpPort(port);
      Main.getConfig().setLogLevel(jComboBoxLogLevel.getSelectedIndex());
      Main.getConfig().setAdmonLocal(jComboBoxLocal.getSelectedItem().toString());

      String cfgFile = System.getProperty(PropertyEnum.PROPERTY_ADMON_GUI_CFG_FILE.getKey());
      if (cfgFile == null)
      {
         cfgFile = Main.getConfig().getCfgFile();
      }

      if (Main.getConfig().writeConfigFile(new File(cfgFile)))
      {
         dispose();
      }
      else
      {
    	  JOptionPane.showMessageDialog(null, Main.getLocal().getString("Could not write configuration file"), Main.getLocal().getString("Write failed"),
            JOptionPane.ERROR_MESSAGE);
      }
}//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
      this.abortPushed = true;
      this.dispose();
}//GEN-LAST:event_jButtonCloseActionPerformed

   public boolean getAbortPushed()
   {
      return this.abortPushed;
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonClose;
   private javax.swing.JButton jButtonSave;
   private javax.swing.JComboBox<String> jComboBoxLogLevel;
   private javax.swing.JComboBox<String> jComboBoxLocal;
   private javax.swing.JLabel jLabelHostname;
   private javax.swing.JLabel jLabelLogLevel;
   private javax.swing.JLabel jLabelLocal;
   private javax.swing.JLabel jLabelPort;
   private javax.swing.JLabel jLabelResolution;
   private javax.swing.JPanel jPanelDialog;
   private javax.swing.JScrollPane jScrollPaneDescription;
   private javax.swing.JTextArea jTextArea1;
   private javax.swing.JTextField jTextFieldHostname;
   private javax.swing.JTextField jTextFieldPort;
   private javax.swing.JTextField jTextResolution;
   // End of variables declaration//GEN-END:variables
}
