package com.beegfs.admon.gui.common.enums;


import com.beegfs.admon.gui.common.tools.DefinesTk;



public enum MetaOpsEnum
{
   META_OPS_IP("client IP", DefinesTk.CLIENT_STATS_COLUMN_WIDTH_IP),
   META_OPS_OPSUM("sum", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_ACK("ack", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_CLOSE("close", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_GETENTRYINFO("entInf", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_GETNODEINFO("nodeInf", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_FINDOWNER("fndOwn", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_LINK("lnk", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_MKDIR("mkdir", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_MKFILE("create", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_READDIR("rddir", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_REFRESHENTRYINFO("refrEnt", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_REQUESTMETADATA("mdsInf", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_RMDIR("rmdir", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_RMLINK("rmLnk", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_MOVINGDIRINSERT("mvDirIns", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_MOVINGFILEINSERT("mvFiIns", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_OPEN("open", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_RENAME("ren", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_SETCHANNELDIRECT("setChDrct", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_SETATTR("sAttr", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_SETDIRPATTERN("sDirPat", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_STAT("stat", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_STATFS("statfs", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_TRUNCATE("trunc", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_SYMLINK("symlnk", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_UNLINK("unlnk", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_LOOKUPINTENT_SIMPLE("lookLI", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_LOOKUPINTENT_STAT("statLI", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_LOOKUPINTENT_REVALIDATE("revalLI", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_LOOKUPINTENT_OPEN("openLI", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_LOOKUPINTENT_CREATE("createLI", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_MIRRORMETADATA("mirrorMD", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_HARDLINK("hardlnk", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_FLOCKAPPEND("flckAp", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_FLOCKENTRY("flckEn", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_FLOCKRANGE("flckRg", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_UPDATEDIRPARENT("dirparent", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_LISTXATTR("listXA", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_GETXATTR("getXA", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_REMOVEXATTR("rmXA", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH),
   META_OPS_SETXATTR("setXA", DefinesTk.CLIENT_STATS_DEFAULT_COLUMN_WIDTH);

   private final String label;
   private final int columnWidth;

   MetaOpsEnum(String label, int columnWidth)
   {
      this.label = label;
      this.columnWidth = columnWidth;
   }

   public String getLabel()
   {
      return label;
   }

   public int getColumnWidth()
   {
      return columnWidth;
   }
}
