#ifndef MGMTD_STORAGETKEX_H_
#define MGMTD_STORAGETKEX_H_

#define STORAGETK_FORMAT_MIN_VERSION        4
#define STORAGETK_FORMAT_LONG_NODE_IDS      4
#define STORAGETK_FORMAT_7_1                5
#define STORAGETK_FORMAT_STATES_META        "nodeStates"
#define STORAGETK_FORMAT_STATES_STORAGE     "targetStates"

#endif /* STORAGETKEX_H_ */
