#ifndef MGMTD_STORAGETKEX_H_
#define MGMTD_STORAGETKEX_H_

#define STORAGETK_FORMAT_MIN_VERSION        2
#define STORAGETK_FORMAT_SHORTS_NODE_IDS    3
#define STORAGETK_FORMAT_LONG_NODE_IDS      4
#define STORAGETK_FORMAT_STATES_META        "nodeStates"
#define STORAGETK_FORMAT_STATES_STORAGE     "targetStates"

#endif /* STORAGETKEX_H_ */
